USE [master]
GO

/****** Object:  Database [WideWorldImporters]    Script Date: 06.02.2023 20:21:42 ******/
CREATE DATABASE [Salary_work_shift_shop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SWSS_Primary', FILENAME = N'C:\Salary DB\Salary_work_shift_shop.mdf' , SIZE = 2097152KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SWSS_Log', FILENAME = N'C:\Salary DB\WideWorldImporters.ldf' , SIZE = 233472KB , MAXSIZE = UNLIMITED , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

--IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
--begin
--EXEC [WideWorldImporters].[dbo].[sp_fulltext_database] @action = 'enable'
--end
--GO

--ALTER DATABASE [WideWorldImporters] SET ANSI_NULL_DEFAULT OFF 
--GO

--ALTER DATABASE [WideWorldImporters] SET ANSI_NULLS OFF 
--GO

--ALTER DATABASE [WideWorldImporters] SET ANSI_PADDING OFF 
--GO

--ALTER DATABASE [WideWorldImporters] SET ANSI_WARNINGS OFF 
--GO

--ALTER DATABASE [WideWorldImporters] SET ARITHABORT OFF 
--GO

--ALTER DATABASE [WideWorldImporters] SET AUTO_CLOSE OFF 
--GO

--ALTER DATABASE [WideWorldImporters] SET AUTO_SHRINK OFF 
--GO

--ALTER DATABASE [WideWorldImporters] SET AUTO_UPDATE_STATISTICS ON 
--GO

--ALTER DATABASE [WideWorldImporters] SET CURSOR_CLOSE_ON_COMMIT OFF 
--GO

--ALTER DATABASE [WideWorldImporters] SET CURSOR_DEFAULT  GLOBAL 
--GO

--ALTER DATABASE [WideWorldImporters] SET CONCAT_NULL_YIELDS_NULL OFF 
--GO

--ALTER DATABASE [WideWorldImporters] SET NUMERIC_ROUNDABORT OFF 
--GO

--ALTER DATABASE [WideWorldImporters] SET QUOTED_IDENTIFIER OFF 
--GO

--ALTER DATABASE [WideWorldImporters] SET RECURSIVE_TRIGGERS OFF 
--GO

--ALTER DATABASE [WideWorldImporters] SET  DISABLE_BROKER 
--GO

--ALTER DATABASE [WideWorldImporters] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
--GO

--ALTER DATABASE [WideWorldImporters] SET DATE_CORRELATION_OPTIMIZATION OFF 
--GO

--ALTER DATABASE [WideWorldImporters] SET TRUSTWORTHY OFF 
--GO

--ALTER DATABASE [WideWorldImporters] SET ALLOW_SNAPSHOT_ISOLATION OFF 
--GO

--ALTER DATABASE [WideWorldImporters] SET PARAMETERIZATION SIMPLE 
--GO

--ALTER DATABASE [WideWorldImporters] SET READ_COMMITTED_SNAPSHOT OFF 
--GO

--ALTER DATABASE [WideWorldImporters] SET HONOR_BROKER_PRIORITY OFF 
--GO

--ALTER DATABASE [WideWorldImporters] SET RECOVERY SIMPLE 
--GO

--ALTER DATABASE [WideWorldImporters] SET  MULTI_USER 
--GO

--ALTER DATABASE [WideWorldImporters] SET PAGE_VERIFY CHECKSUM  
--GO

--ALTER DATABASE [WideWorldImporters] SET DB_CHAINING OFF 
--GO

--ALTER DATABASE [WideWorldImporters] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
--GO

--ALTER DATABASE [WideWorldImporters] SET TARGET_RECOVERY_TIME = 0 SECONDS 
--GO

--ALTER DATABASE [WideWorldImporters] SET DELAYED_DURABILITY = DISABLED 
--GO

--ALTER DATABASE [WideWorldImporters] SET ACCELERATED_DATABASE_RECOVERY = OFF  
--GO

--ALTER DATABASE [WideWorldImporters] SET QUERY_STORE = ON
--GO

--ALTER DATABASE [WideWorldImporters] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 3000, INTERVAL_LENGTH_MINUTES = 15, MAX_STORAGE_SIZE_MB = 500, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 1000, WAIT_STATS_CAPTURE_MODE = ON)
--GO

--ALTER DATABASE [WideWorldImporters] SET  READ_WRITE 
GO


